# Generated by Django 3.2.3 on 2021-11-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20211106_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organ',
            field=models.CharField(default='', max_length=20),
        ),
    ]
